# -*- coding: utf-8 -*-
"""
Created on Thu Feb  3 21:48:45 2022

@author: think
"""

f1=open("缅语原文.txt","r",encoding="utf-8")

x=f1.read()
for i in x:
    if i=='A':
        print('ဗ',end=' ')
    elif i=='r':
        print('မ',end=' ')
    elif i=='m':
        print('ာ',end=' ')
    elif i=='j':
        print('ြ',end=' ')
    elif i=='y':
        print('ပ',end=' ')
    elif i=='n':
        print('ည',end=' ')
    elif i=='f':
        print('်',end=' ')
    elif i=='u':
        print('က',end=' ')
    elif i=='G':
        print('ွ',end=' ')
    elif i=='e':
        print('န',end=' ')
    elif i=='L':
        print('ူ',end=' ')
    elif i=='p':
        print('စ',end=' ')
    elif i=='g':
        print('ါ',end=' ')
    elif i=='w':
        print('တ',end=' ')
    elif i=='D':
        print('ဓ',end=' ')
    elif i=='.':
        print('၏',end=' ')
    elif i=='z':
        print('ဖ',end=' ')
    elif i=='J':
        print('ဲ',end=' ')
    elif i=='@':
        print('့',end=' ')
    elif i==';':
        print('း',end=' ')
    elif i=='t':
        print('အ',end=' ')
    elif i=='k':
        print('ု',end=' ')
    elif i=='c':
        print('ခ',end=' ')
    elif i=='s':
        print('ျ',end=' ')
    elif i=='K':
        print('ု',end=' ')
    elif i=='H':
        print('ံ',end=' ')
    elif i=='O':
        print('ဥ',end=' ')
    elif i=='a':
        print('ေ',end=' ')
    elif i=='E':
        print('န',end=' ')
    elif i=='S':
        print('ှ',end=' ')
    elif i=='i':
        print('င',end=' ')
    elif i=='h':
        print('့',end=' ')
    elif i=='ð':
        print('ြု',end=' ')
    elif i=='x':
        print('ထ',end=' ')
    elif i=='o':
        print('သ',end=' ')
    elif i=='d':
        print('ိ',end=' ')
    elif i=='b':
        print('ဘ',end=' ')
    elif i=='v':
        print('လ',end=' ')
    elif i=='?':
        print('။',end=' ')
    elif i=='[':
        print('ဟ',end=' ')
    elif i=="'":
        print('ဒ',end=' ')
    elif i=='&':
        print('ရ',end=' ')
    elif i=='X':
        print('ဌ',end=' ')
    elif i==',':
        print('ယ',end=' ')
    elif i=='+':
        print('ြ',end=' ')
    elif i=='l':
        print('ူ',end=' ')
    elif i=='/':
        print(',',end=' ')
    elif i=='q':
        print('ဆ',end=' ')
    elif i=='$':
        print('ွှ',end=' ')
    elif i=='ò':
        print('ြု',end=' ')
    elif i=='*':
        print('ဂ',end=' ')
    elif i=='~':
        print('္',end=' ')
    elif i=='#':
        print('ှျ',end=' ')
    elif i=='æ':
        print('ွ',end=' ')
    elif i=='I':
        print('၍',end=' ')
    elif i=='º':
        print('ြ',end=' ')
    elif i=='C':
        print('ဃ',end=' ')
    elif i=='=':
        print('ြ',end=' ')
    elif i=='|':
        print('ျွ',end=' ')
    elif i=='‚':
        print('၎',end=' ')
    elif i=='W':
        print('္တ',end=' ')
    elif i==':':
        print('ါ်',end=' ')
    elif i=='ó':
        print('ြု',end=' ')
    elif i=='ñ':
        print('ြု',end=' ')
    elif i=='P':
        print('စ',end=' ')
    elif i=='±':
        print('ရ',end=' ')
    elif i=='B':
        print('ဘ',end=' ')
    elif i=='}':
        print('ြ',end=' ')
    elif i=='!':
        print('ည',end=' ')
    elif i=='_':
        print('ူ',end=' ')
    elif i=='%':
        print('ဏ',end=' ')
    elif i=='Q':
        print('ခ',end=' ')
    elif i=='Z':
        print('ဇ',end=' ')
    elif i=='"':
        print('မ',end=' ')
    elif i=='T':
        print('ဤ',end=' ')
    elif i==r"\\":
        print('ဿ',end=' ')
    elif i=='ª':
        print('ှူ',end=' ')
    elif i=='Y':
        print('၌',end=' ')
    elif i=='ˆ':
        print('ထ',end=' ')
    elif i=='‡':
        print('ှ',end=' ')
    elif i=='¹':
        print('ြ',end=' ')
    elif i=='¸':
        print('ွှ',end=' ')
    elif i=='¿':
        print('ဏ္ဌ',end=' ')
    elif i=='N':
        print('ဒ',end=' ')
    elif i=='¾':
        print('ဏ္ဍ',end=' ')
    elif i=='…':
        print('ဇ',end=' ')
    elif i=='\n':
        print()
    elif i=='':
        print(i)
print("完成")
f1.close()